### ISSUE TITLE
Rewrite in Rust 🦀

### ISSUE THREAD

**Issue by Sleppo04** [Knoficooki/QualityGame#1]
# Rewrite in Rust
## Why?
This awesome application is in dire need of a rewrite in a modern, understandable language that is not C (and has a borrow checker, also unlike C (and is good, also also unlike C))
My proposal: Rust 🦀
This also enables this application to be blazingly fast 🚀, and safe 🔐 unlike the current version written in ancient C.

## How?
https://www.youtube.com/watch?v=5C_HPTJg5ek

**Comment by Knoficooki** [comment]
XD Dumbest thing I ever heard... good one

**Comment by Sleppo04** [comment]
> XD Dumbest thing I ever heard... good one

# Delete your comment
## Why
Because your comment is, in fact, unnecessary, and doesn't address my issue in the slightest. You may want to change you behavior on this platform, and have a look at the [GitHub community guidelines.](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines)

## How?
On the top right of the comment field, there should be a small icon with three dots on it. Click it. In the menu that opens, there should be a label with red text that says `delete.` Click it.

**Comment by Knoficooki** [comment]
I am sorry to correct you but there is in fact no button labeled "delete".
